### ISSUE TITLE
Add support for Scala 2.11.x

### ISSUE THREAD

**Issue by cduicu** [orrsella/sbt-stats#6]
Please add support for Scala 2.11.x.

**Comment by orrsella** [comment]
Seeing as sbt [currently only runs/builds on Scala 2.10.x](http://stackoverflow.com/questions/23282469/does-sbt-builds-againts-scala-2-11), I'm not sure I understand what you mean. To the best of my knowledge you can use `sbt-stats` for a project that's set to run with `scalaVersion := 2.11.x` (tho again, sbt itself uses Scala 2.10 to run). Have you experienced otherwise?

**Comment by cduicu** [comment]
Hmm... I may have jumped to conclusions based on the messages. In fact, I guess the problem is with artifact download. Searching Maven (http://search.maven.org/#search%7Cga%7C1%7Ccom.orrsella.sbt-stats) I see the 1.0.5 returned in the results but whenever I try to get the pom or jar the page is missing.

**Comment by orrsella** [comment]
That's very strange, since the published version is in Maven central, with all files included:

[http://repo1.maven.org/maven2/com/orrsella/sbt-stats_2.10_0.13/1.0.5/](http://repo1.maven.org/maven2/com/orrsella/sbt-stats_2.10_0.13/1.0.5/)

Do you experience issues when adding the plugin to your build and failing to resolve/download it? If so, can you please add the error messages you're getting?

**Comment by cduicu** [comment]
Yes,  it is strange. Here is the message from activator:

[info] Resolving com.orrsella#sbt-stats;1.0.5 ...
[warn]  module not found: com.orrsella#sbt-stats;1.0.5
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.orrsella/sbt-stats/scala_2.10/sbt_0.13/1.0.5/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.orrsella/sbt-stats/scala_2.10/sbt_0.13/1.0.5/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\cristiand\.ivy2\local\com.orrsella\sbt-stats\scala_2.10\sbt_0.13\1.0.5\ivys\ivy.xml
[warn] ==== my-maven-proxy-releases: tried
[warn]   http://localhost:8081/artifactory/releases/com/orrsella/sbt-stats_2.10_0.13/1.0.5/sbt-stats-1.0.5.pom
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/orrsella/sbt-stats_2.10_0.13/1.0.5/sbt-stats-1.0.5.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.orrsella#sbt-stats;1.0.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.orrsella:sbt-stats:1.0.5 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.orrsella:sbt-stats:1.0.5 (scalaVersion=2.10, sbtVersion=0.13) (C:\home\playcommons\project\plugins.sbt#L10-11)
[warn]            +- default:playcommons-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.orrsella#sbt-stats;1.0.5: not found

It should normally be resolved with maven. I have Maven proxied via a local Artifactory. The message I get from the proxy is: "Failed to transform pom file: The target deployment path 'com/orrsella/sbt-stats_2.10_0.13/1.0.5/sbt-stats-1.0.5.pom' does not match the POM's expected path prefix 'com/orrsella/sbt-stats/1.0.5'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
It would seem that it tries to match the artifact name with the path and that is where it fails as the path contains the scala and sbt versions in the artifact name.

**Comment by orrsella** [comment]
I think that the problem is that sbt plugins have a different path prefix then "regular" jar dependencies. For example:

```
sbt-stats_2.10_0.13/
# vs
tumblr4s_2.10/
```

(both from the [example above](http://repo1.maven.org/maven2/com/orrsella/).)

My guess is that Artifactory isn't configured properly to work with such a prefix (artifact_id_rev_sbt-rev). Do you want to maybe give it a try without the local artifactory, and directly against Maven central?

**Comment by cduicu** [comment]
That is correct! Once I added Maven repo it worked. 

resolvers += "Maven Repo" at "http://repo1.maven.org/maven2/"

I will have to figure out how to configure my proxy to work with sbt plugins too. Thanks for your support - I think the issue is closed now.

**Comment by orrsella** [comment]
Glad to help.
